API 연동
FoodieZone/Frontend pull request #24
Opened 2023-12-05 01:41 UTC by HwangYoonSeong

### Ticket
https://foodiezone.atlassian.net/browse/FE-24

### Purpose
API 연동 및 react query 적용

2023-12-05 04:44 UTC, gunwoongPark commented on src/pages/Recommend/index.tsx
> +						<StoreAddress>{recommended?.address}</StoreAddress>
ask;

optional chaining 사용했으면 nullish 병합연산자 (`??`) 같이 써주는건 어떨까요!?!?

2023-12-05 04:45 UTC, gunwoongPark commented on src/pages/LocationAgree/index.tsx
> +	}, [isSuccess]);
p3;

early return 활용해보면 어떨까요!?!?

2023-12-05 04:46 UTC, gunwoongPark commented on src/queries/restaurant.ts
> +	return restaurants;
ask;

혹시 예외처리 어디서 진행되는지 확인 부탁드립니다 !!

2023-12-05 04:46 UTC, gunwoongPark approved these changes

2023-12-05 04:49 UTC, taese0ng commented on src/pages/Recommend/index.tsx
> +						<StoreAddress>{recommended?.address}</StoreAddress>
애초에 왜 값이 없을수도있다는거죠? 옵셔널로 볼게 아닌거같은데요

2023-12-05 04:50 UTC, taese0ng commented
@gunwoongPark 리뷰완료가 될때까지 어프롭은 안하는게맞는거같아여

2023-12-05 04:58 UTC, taese0ng commented on src/pages/Recommend/index.tsx
> +	const { latitude, longitude } = useRecoilValue(locationState);
웹기반이다보니까 새로고침이 일어났을경우 recoil값이 날라갈거같은데 세션스토리지로 이관하는건 어떨까요
아니면 새로고침해도 리코일 값 남게 하는 라이브러리있는데 그거 추가해서 로컬스토리지 리코일로 관리하는것도 방법일거같습니다.

2023-12-05 04:58 UTC, taese0ng commented on src/pages/Recommend/index.tsx
> +						<StoreAddress>{recommended?.address}</StoreAddress>
만약 옵셔널일 가능성이있다면 없는경우 해당 컴포넌트 열 자체를 랜더링하지않게 해야할거같습니다.

2023-12-05 13:31 UTC, gunwoongPark requested changes

2023-12-05 13:31 UTC, gunwoongPark commented on src/pages/Recommend/index.tsx
> +						<StoreAddress>{recommended?.address}</StoreAddress>
> 애초에 왜 값이 없을수도있다는거죠? 옵셔널로 볼게 아닌거같은데요

맞네여.. 꼼꼼하게 봤어야했는데;; 불필요해보이는 optional chaining 같습니다 !!

2023-12-05 13:31 UTC, gunwoongPark commented on src/pages/WorldCup/index.tsx
>  				))}
p3;

el 보다는 더 직관적인 식별자명을 활용하면 어떨까요 !! 예를들어 `slicedCandidate` ???

2023-12-05 13:31 UTC, gunwoongPark commented on src/pages/WorldCupResult/index.tsx
>  	}, []);
p3;

단 한 번 사용되는 로직이면 useMount 느낌으로 커스텀 훅 만들어서 활용하면 어떨까요!?

2023-12-05 13:31 UTC, gunwoongPark commented on src/queries/rounds.ts
> +
p3;

`?`전에 `/`없어도 돼요!!

2023-12-11 01:38 UTC, gunwoongPark approved these changes

2023-12-11 01:38 UTC, gunwoongPark commented on src/pages/WorldCupResult/index.tsx
>  	}, []);
굳이 재사용을 제외하더라도 저는 보통 훅으로 빼서 사용하긴 하는데 스타일 차이일거같네요 :)

2023-12-12 00:34 UTC, taese0ng approved these changes

2023-12-16 11:05 UTC, merged