[FE-9] feat: useIsWebView 훅 개발
FoodieZone/Frontend pull request #3
Opened 2023-08-08 13:44 UTC by taese0ng

[티켓](https://foodiezone.atlassian.net/browse/FE-9?atlOrigin=eyJpIjoiZGYxOTQ0MTI2ODc1NDUzM2IwNGM2Zjk4NGI4MjkxYzYiLCJwIjoiaiJ9)

ios, android에서 웹뷰로 사용될때 구분할 수 있는 커스텀 훅 개발
- 1차적으로 UserAgent로 검증
- 2차로 안드로이드, ios에서 사용가능한 브릿지함수를 확인함으로 검증
- 이중 하나라도 조건에 맞는다면 webView로 간주.

2023-08-11 05:09 UTC, gunwoongPark approved these changes

2023-08-11 05:09 UTC, gunwoongPark commented on src/hooks/useIsWebView.ts
> +	const [isWebView, setIsWebView] = useState<boolean>(false);
@taese0ng 저희 함수 생성할 때, 선언식으로 할지, 표현식으로 할지도 결정하면 좋을듯해요~

2023-08-11 05:09 UTC, gunwoongPark commented on src/hooks/useIsWebView.ts
> +			typeof window.webkit.messageHandlers.WebViewBridge !== 'undefined';
@taese0ng lodash-es 라이브러리 설치해서 여러 유틸함수들 활용하는거 어떨가요?? 

isUndfined(), isNotUndefinde 등 활용하면 코드 가독성이 더 좋을듯해서요

2023-08-11 09:04 UTC, taese0ng commented on src/hooks/useIsWebView.ts
> +	const [isWebView, setIsWebView] = useState<boolean>(false);
전에 리뷰에서 말했듯이 메인 함수, 컴포넌트는 function으로 선언하고 나머지 들을 const로 선언하는게 구분하기 쉬워보이는데 어떻게생각합니까

2023-08-11 09:12 UTC, taese0ng commented on src/hooks/useIsWebView.ts
> +			typeof window.webkit.messageHandlers.WebViewBridge !== 'undefined';
fa403aa1baa6cc5786b910416b4c20f5c6e4bb96
수정했습니다. 확인 부탁드려요

2023-08-11 12:29 UTC, HwangYoonSeong commented on src/hooks/useIsWebView.ts
> +	const [isWebView, setIsWebView] = useState<boolean>(false);
동의합니다~

2023-08-11 12:41 UTC, HwangYoonSeong requested changes

2023-08-11 12:41 UTC, HwangYoonSeong commented on src/hooks/useIsWebView.ts
> +		const isWebViewWithBridge = isWebViewUserAgent || isAndroidWebView || isIOSWebView;
여기서 바로 `isWebViewUserAgent || isAndroidWebView || isIOSWebView` 이 값을 바로 리턴하면 굳이 커스텀 훅일 필요가 없어보이는데 어떻게 생각하시나요?? 

useEffect 내에서 실행되고, isWebView가 state로 관리되어야하는 특별한 이유가 있을까요??

2023-08-11 22:30 UTC, taese0ng commented on src/hooks/useIsWebView.ts
> +		const isWebViewWithBridge = isWebViewUserAgent || isAndroidWebView || isIOSWebView;
@HwangYoonSeong 유틸함수로 만들어도 사용은 가능하겠지만 그렇게되면 사용처에서 일일이 useEffect내에서 상태를 받아오고 저장해야하는 불편함이 있습니다. 지금당장은 사용처가 많지않지만 로그인이나 다른 기능들에 webView인지 판단하는 로직이 들어간다면 재사용해야하고 그때마다 각 컴포넌트에서 UseEffect에서 유틸함수를 돌리고 그 상태를 컴포넌트의 지역state에 저장해서 사용해야하죠. 그런 불편함을 없앨수 있습니다.

2023-08-15 14:32 UTC, taese0ng commented on src/hooks/useIsWebView.ts
> +		const isWebViewWithBridge = isWebViewUserAgent || isAndroidWebView || isIOSWebView;
@HwangYoonSeong 넵 웹뷰인지 아닌지에 따라 UI로직도 달라질수 있어서 마운트될때 확인해서 분기처리 할수있도록 해주는 것도 필요합니다. 질문의 의도를 잘모르겠는데 그러면 커스텀 훅 말고 유틸함수로 만들기를 원하시는걸까여?? 유틸함수로 했을때 이점이 있다면 설명해주시면 좋을거같아요

2023-08-15 14:37 UTC, gunwoongPark commented on src/hooks/useIsWebView.ts
> +			typeof window.webkit.messageHandlers.WebViewBridge !== 'undefined';
@taese0ng 제가 알기로 기본 lodash 사용하면 트리셰이킹이 안되는 이슈가 있다고 해요 그래서 혹시

https://www.npmjs.com/package/@types/lodash-es

해당 라이브러리로 대체 가능할까요 ??

2023-08-15 15:08 UTC, gunwoongPark commented on src/hooks/useIsWebView.ts
> +	const [isWebView, setIsWebView] = useState<boolean>(false);
반 영 완 료

2023-08-21 02:49 UTC, taese0ng commented on src/hooks/useIsWebView.ts
> +			typeof window.webkit.messageHandlers.WebViewBridge !== 'undefined';
79962dd2007feb6a9b04f0f25f2698d0fbf88d1f

좋은 정보 알려줘서 고맙슴다~ 이런건 몰랐네여 굿굿
교체완료했습니다

2023-08-22 12:59 UTC, HwangYoonSeong commented on src/hooks/useIsWebView.ts
> +		const isWebViewWithBridge = isWebViewUserAgent || isAndroidWebView || isIOSWebView;
웹뷰인지 구분하기 위함이 주 목적인 경우라면 사용성 측면을 더 고려해볼 필요가 있다고 생각합니다. 커스텀 훅으로 구현할 경우 커스텀 훅 사용 조건에 제약이 있기 때문에 리액트 컴포넌트 내에서만 동작하는 반면 유틸함수의 경우 사용에 제약이 없으므로 유틸함수로 구현할 수 있는 경우라면 유틸함수로 구현하는 것이 사용성 측면에서 더 좋다고 판단됩니다. 

또한, 이 경우에 해당 되지는 않지만 유지 보수 측면에서도 커스텀 훅 사용에 주의해야할 점도 고려해보면 좋을 것 같아서 관련 링크 첨부합니다. 
https://medium.com/finda-tech/%ED%95%80%EB%8B%A4%EC%97%90%EC%84%9C-%EC%93%B0%EB%8A%94-react-custom-hooks-1a732ce949a5

2023-08-23 01:27 UTC, taese0ng commented on src/hooks/useIsWebView.ts
> +		const isWebViewWithBridge = isWebViewUserAgent || isAndroidWebView || isIOSWebView;
@HwangYoonSeong 
사용성 측면에서 고려했을때 유틸함수로 사용하면 더 불편함을 야기할 것입니다.
예를들어
```
function App() {
   const [isWebView, setIsWebView] = useState(false);

   useEffect(()=> {
      setIsWebView(utilWebView())
   },[])
}
```
이런식으로 사용처마다 불필요한 state를 생성하고 effect처리를 해야합니다. 마운트 전에 웹뷰인지 아닌지 확인한다면 로직상 불확실하기때문에 저런방식으로 사용해야하는데, 커스텀훅으로 사용한다면 그러한 불편함이 사라집니다.
이런걸 고려했을때도 사용성 측면에서 유틸함수가 더 뛰어나다라고는 생각이 안드는데 유틸함수로 사용했을때의 이점을 더 확실히 예시로 들어주시면 좋을것 같습니다.

추가로 웹뷰 구분에 있어서는 리액트 컴포넌트에서만 사용이 되며, 다른곳에 사용이 될 것이라고 보이지 않습니다.

2023-08-27 09:17 UTC, HwangYoonSeong commented on src/hooks/useIsWebView.ts
> +		const isWebViewWithBridge = isWebViewUserAgent || isAndroidWebView || isIOSWebView;
@taese0ng 
isWebView가 구분되어야할 경우 중 위치 동의를 받는 부분을 예로 들어보겠습니다. 
```js
const onClickPositionAgreemnet = () => {
    if (isWebView()) {
      // NATIVE에서 위치 정보를 가져옴
      addNativeMessageListener(messageListener, { once: true })
      postMessage('getGeolocation', {
        timeout: 5000,
        needAndroidLocationEnabler: true,
      })
    } else {
      // 웹에서 위치 정보를 가져옴
      navigator.geolocation.getCurrentPosition(
        getPositionSuccessCallback,
        getPositionFailureCallback,
        { timeout: 5000, enableHighAccuracy: false },
      )
    }
  }
```
컴포넌트 내 상태로 저장해서 웹뷰인지 여부에 따라 UI가 변경되는 경우보다 
특정 위치에서 웹뷰인지 여부를 확인하는 최소 기능으로만 사용되는 경우로 고려하여 
그 이후 작업은 자유롭게 핸들링할 수 있도록 구현하는게 어떨까요??

2023-08-28 00:02 UTC, taese0ng commented on src/hooks/useIsWebView.ts
> +		const isWebViewWithBridge = isWebViewUserAgent || isAndroidWebView || isIOSWebView;
@HwangYoonSeong 
네 말씀주신대로 사용할수도있지만 커스텀훅으로 했을경우에는 위의 예시로 들어준 내용까지 한번에 커버가 가능합니다.
만약 설명주신대로 유틸함수로 하게되면 예를들어 한 컴포넌트에서 로직에서도 사용하고, UI에도 영향을 끼치는 상황까지왔을때 두번의 함수호출, 그리고 내부에서 상태관리까지 추가적으로 늘어나서 코드가 간결해지지 않는 문제가 생길 수 있습니다. 어떤방법이 무조건 좋다는 아니지만 다양한방면에서 커버가 가능한 커스텀훅이 좋지않을까 생각이 드네요. 그리고 웹뷰인지 아닌지는 미리 그 페이지가 렌더링됐을때 미리 값을 가지고 그 값으로 빠르게 이용하는것이 더 안정적일 것이라고봅니다. 사용할때마다 확인해서 분기처리하는것은 비용적으로도 좋지않다고 생각이 드네요. 지금 예시는 UI쪽은 전혀 고려하지않은 상태만을 예시로 들어준 것같습니다.

2023-08-28 01:24 UTC, HwangYoonSeong approved these changes

2023-08-28 01:40 UTC, merged